spring:
  application:
    name: COMMA
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000      # 1시간 (3,600초)
  refresh-token-expiration: 1209600000  # 2주 (1,209,600초)

kakao:
  client-id: ${KAKAO_CLIENT_ID}

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}

apple:
  client-id: ${APPLE_CLIENT_ID}
  team-id: ${APPLE_TEAM_ID}
  key-id: ${APPLE_KEY_ID}
  private-key: ${APPLE_PRIVATE_KEY}
